### ISSUE TITLE
Edit doesn't seem to do anything

### ISSUE THREAD

**Issue by dharmaturtle** [gustavnavar/Grid.Blazor#12]
**Describe the bug**
On the demo page "All features", if you click `Edit` on the right, nothing becomes editable.

**To Reproduce**
1. Go to http://gridblazor.azurewebsites.net/gridsample
2. Click on `Edit`
3. Observe nothing happen

**Expected behavior**
I expected some text boxes to appear, prefilled with the previous information.

**Screenshots**
![image](https://user-images.githubusercontent.com/1278803/62336555-6854e900-b496-11e9-8aa6-30a9ed16e319.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 75

**Comment by gustavnavar** [comment]
It was not doing anything because there was a missing feature in the GridBlazor component.

I've uploaded a new version of GridBlazor that includes grid state serialization (page, filtering, sorting, etc.). Now it's possible to navigate to another page and return to the grid in the same state.

Included samples in the solution and the demo support now editin.

**Comment by dharmaturtle** [comment]
Awesome, this looks really cool. Thanks!
