### ISSUE TITLE
Is there a way to display images?

### ISSUE THREAD

**Issue by faina09** [gustavnavar/Grid.Blazor#127]
in Model Category there is a field containing an image:

```
        [JsonIgnore]
        public byte[] Picture { get; set; }
```

that currently is not displayed (I see just the data type `System.Byte[]` if I try to display this column).
Are you planned a render for types like these (img, jpg, doc ,...) ?

**Comment by gustavnavar** [comment]
Yes, I've just uploaded a sample here https://gridblazor.azurewebsites.net/gridsample

You can use ```RenderValueAs``` and ```RenderComponentAs``` methods. If you want to show just tje image maybe its easier with ```RenderValueAs```:

```c#
c.Add().Encoded(false).Sanitized(false).SetWidth("5%").SetCrudHidden(true)
    .RenderValueAs(o => $"<img width='50' height='50' src='data:image/bmp;base64,{o.Employee.Base64String}' />");
```

You have to send the byte array as a base64 string. In the case of the sample the conversion is a little bit more complex because the way the Northwind database store images. But in normal cases just a conversion to base64 string should be enough.
