### ISSUE TITLE
Filter pop overs are getting chopped off

### ISSUE THREAD

**Issue by prabhakarreddy1234** [gustavnavar/Grid.Blazor#193]
As shown in the screenshot below, the filter popovers are getting chopped off and unusable. If popover flips to left if there is no space left on right then it help view the pop over in all screens.

![image](https://user-images.githubusercontent.com/1984707/88477424-d44a2000-cf37-11ea-8a14-a83e720e224d.png)

**Comment by prabhakarreddy1234** [comment]
@gustavnavar  Can the filter icons on the header be put just beside the header label ? 

Also, it would be useful to have a setting which decides simple text filter or more advanced current filter.

**Comment by adugasBID** [comment]
I got the same issue.
It happens when the control is inside a "modal" window having an overflow-x or overflow-y value.
My window has those properties:
`max-height: calc(100vh - 220px);
overflow-y: auto;
overflow-x: hidden;`

It would be nice if the control detected this scenario. I wouldn't mind having to manually specify the parent size so the component knowns the boundaries to respect.

**Comment by gustavnavar** [comment]
Package version 1.8.3 should solve this issue

**Comment by gustavnavar** [comment]
Use Nuget package version 1.8.4. 

No source code changes, but nuget package 1.8.3 did not include all dlls.
