### ISSUE TITLE
Checkbox not working

### ISSUE THREAD

**Issue by quangdat88** [gustavnavar/Grid.Blazor#20]
Checkbox is not working when show in front-end?
Click on checkbox - this checkbox not checked?
![image](https://user-images.githubusercontent.com/4156611/66972702-9cb46a80-f0bf-11e9-8a7e-4ec09a38d1de.png)

**Comment by gustavnavar** [comment]
I think this happens because the default value for the "Selectable" feature is currently "true".  ASP.NET Core 3.0 does not allow event propagation stop. So when you click on the checkbox the event is propagated to the GridBlazor component. ASP.NET version 3.1 is supposed to solve this issue. 

You should try to add ".Selectable(false)" when the GridClient object is created:

´´´c#
var client = new GridClient<Order>(url, query, false, "ordersGrid", ColumnCollections.OrderColumns, locale)
            .Sortable()
            .Filterable()
            .Selectable(false)
            .WithMultipleFilters()
            .WithGridItemsCount();
´´´  
I will change the default value of "Selectable" in the following version to avoid this issue.

**Comment by quangdat88** [comment]
Thanks you!
