### ISSUE TITLE
sort icon shows gibberish

### ISSUE THREAD

**Issue by igorgy** [gustavnavar/Grid.Blazor#219]
**Describe the bug**
Doing a test app using odata endpoint guide, and getting incorrect sort icon in 3(firefox, edge, chrome) browsers with different locale.

**Screenshots**
![image](https://user-images.githubusercontent.com/25223758/96615656-41d4d500-130a-11eb-9245-3058713d2cbf.png)

I am setting up columsn like this:

    Action<IGridColumnCollection<User1>> Columns = c =>
    {
        c.Add(o => o.id).Filterable(false);
        c.Add(o => o.firstName).Filterable(true).Sortable(true);
        c.Add(o => o.lastName).Filterable(true).Sortable(true);
        c.Add(o => o.username).Filterable(true).Sortable(true);
        c.Add(o => o.password).Filterable(false).Sortable(true);
    };

And creating client like:

        var client = new GridODataClient<User1>(httpClient, url, query, false, "ordersGrid", Columns, 1)
            .ChangePageSize(true)
            .ClearFiltersButton(true)
            .Searchable()
            .Selectable(true);

**Comment by gustavnavar** [comment]
Sorting icons are up and down unicode arrows (U+2191 and U+2193). 

I think your issue is related with unicode definition on your page and not with locale definition of the grid.

The sample web (https://gridblazor.azurewebsites.net/) has multiple locales and all pages uses this UTF definition on the header:
```html
<meta charset="utf-8">
```

**Comment by igorgy** [comment]
thx! that helped.
