### ISSUE TITLE
Selecting rows at run time

### ISSUE THREAD

**Issue by LeoPiresDeSouza** [gustavnavar/Grid.Blazor#236]
Hi Gustav!
Is there a way to force a row to be selected on Grid load?
Thanks.

**Comment by LeoPiresDeSouza** [comment]
I see that Blazor has an option to select the first row, but I can´t find that option in MVC.

**Comment by gustavnavar** [comment]
GridMvcCore does not support auto selecting the first row. This and other extended features are only supported for Blazor components.

When I develop new features I try to do it for both MVC and Blazor. But some of them are too complex to be developed for MVC because they require c# and javascript changes, so I can only add to GridBlazor library.

If you need some functionality that is only present in GridBlazor, you can use a Blazor component on a MVC project as is described here https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/dotnetcore_blazor/Documentation.md.

I use GridBlazor components in existing  MVC projects as an interim solution until they will be migrated to Blazor. And it works pretty well.

If you run this demo https://github.com/gustavnavar/Grid.Blazor/tree/master/GridMvc.Demo you will find some GridBlazor components embedded in regular razor views using await the ```RenderComponentAsync``` html helper.
