### ISSUE TITLE
Non-blocking query result

### ISSUE THREAD

**Issue by oruchreis** [gustavnavar/Grid.Blazor#340]
Hi,
As far as I saw in source code, `GridServer.ItemsToDisplay` calls blocking `ToList` method of `IQueryable`. This line blocking current thread:
https://github.com/gustavnavar/Grid.Blazor/blob/189cdf670f58cc260e0768a6e86a5a61442cc031/GridCore/GridBase.cs#L112
Are there any plans to implement async version of `GridServer` to use non-blocking `ToListAsync` method? Or are there an other way to use `ToListAsync` instead?

**Comment by gustavnavar** [comment]
Hi,

```System.Linq``` does not implement any async method, it only implements the ```ToList``` method.  And ```System.Linq``` is currently the only requirement to build queries in the GridCore package. EF Core is not required.

If we wanted an async implementation to materialize the list of items to be shown on the screen, then EF Core must be used. EF Core includes an extension for ```IQueriable``` object to get an async list. But I didn't want to have this dependency because EF Core is not always used. So using ```ToList``` is a lesser evil.

If you have any idea about this, please let me know.

**Comment by oruchreis** [comment]
I understand that the library should not be depent on EF Core or any other orm, and I agree with that. But it could be solved by an abstraction layer like an interface or something else. For instance of using an interface, it can be capable of running queries in sync and async manner, and someone else like me can implement this interface and register to DI to change behavior of querying like using EF core.

**Comment by gustavnavar** [comment]
GriBlazor 3.2.3 supports one of the following methods to get **ItemsDTO<T>** object:
    * ```server.ItemsToDisplay``` returns the object using the standard ```ToList``` method of the ```IQueryable<T>``` object supplied by ```System.Linq``` package
    * ```await server.GetItemsToDisplayAsync(Func<IQueryable<T>, Task<IList<T>>> toListAsync)``` returns the object using a custom```toListAsync``` method of the ```IQueryable<T>``` object. This method can be supplied by an ORM like EF Core. In this case we can call ```await server.GetItemsToDisplayAsync(async x => await x.ToListAsync())```

**Comment by oruchreis** [comment]
I didn't expect it so fast, I appreciate that thanks.
