### ISSUE TITLE
Groupable: Issue when grouping color

### ISSUE THREAD

**Issue by mythrz** [gustavnavar/Grid.Blazor#48]
**Issue: **
when grouping a property of type System.Drawing.Color it sometimes crashes, other times only gives a warning/exception: System.ArgumentException: 'At least one object must implement IComparable.'
Other properties (of the same class) are working properly: string, DateTimeOffset, int, decimal.

**To Reproduce: **
1. Create a new class, that has a property with System.Drawing.Color.
2. New Grid.Blazor, (tested in server side)
3. Add .Groupable()
4.  Run, group the Color Column
5. System.ArgumentException triggers on server side.

**Expected behavior: **
No Exception should be triggered and it should never crash.

**Desktop:**
 - OS: WIndows
 - Browser: chrome

**Additional context**
I wanted to make a test of it, but I don't know how to group programatically.
![image](https://user-images.githubusercontent.com/44119535/69956963-7032a180-14f9-11ea-86f8-e9cb2e386481.png)

**Comment by mythrz** [comment]
It also affects Sorting. Causes the same exception.

**Comment by gustavnavar** [comment]
```System.Drawing.Color``` is a struct and it not supported as column value because it can not be stored in a database. 

The best option to store a ```System.Drawing.Color``` struct is converting it to a 32-bit ARGB value (https://docs.microsoft.com/en-us/dotnet/api/system.drawing.color.toargb?view=netcore-3.0). Soif you use a 32-bit integer for the column value everything will work as expected.
